const pakutasoUsers = [
  {  "name" : "井隼そら",  "kana" : "いはやそら",  "email" : "ihaya@example.com",  "birthday" : "2021/2/8",  "pref" : "大阪府",  "city" : "門真市",  "town" : "北島町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "慶應義塾大学に通う二年生です。まだまだ不慣れですが、ご希望に応えられるよう精一杯頑張りますので、宜しくお願いします！お仕事、お待ちしております。", "photoIndex": 3 },
  {  "name" : "大川竜弥",  "kana" : "おおかわりゅうや",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "大阪府",  "city" : "門真市",  "town" : "北島町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "自称・日本一インターネットで顔写真が使われているフリー素材モデルです。ぱくたそのモデル兼広報担当としてFacebookページの運用をしております。お仕事ください。", "photoIndex": 5 },
  {  "name" : "茜さや",  "kana" : "あかねさや",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "大阪府",  "city" : "門真市",  "town" : "北島町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "広島なまりが少しぬけない狸顔( ˙ω˙ )よく泣いてよく食べます（むちむちなのはご愛嬌）ミスヤンチャンファイナリスト", "photoIndex": 4},
  {  "name" : "河村友歌",  "kana" : "かわむらゆか",  "email" : "xmasyk0519@gmail.com",  "birthday" : "5月19日",  "pref" : "大阪府",  "city" : "門真市",  "town" : "北島町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "初めまして！河村友歌（かわむらゆか）です！現役大学生でフリーモデルをやってます(^^)♪いつまでも初心を忘れず、新しい挑戦をたくさんしたいと思ってます♪皆様からのお仕事、お待ちしております（＾Ｏ＾☆", "photoIndex": 0 },
  {  "name" : "まめち",  "kana" : "まめち",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "大阪府",  "city" : "門真市",  "town" : "北島町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "自称・日本一インターネットで顔写真が使われているフリー素材モデルです。ぱくたそのモデル兼広報担当としてFacebookページの運用をしております。お仕事ください。", "photoIndex": 2 },
  {  "name" : "段田隼人",  "kana" : "だんだはやと",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "大阪府",  "city" : "門真市",  "town" : "北島町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "どうも段田です。普段は株式会社Hyraxでエンジニアとして働いている豚です。豚なんです。段田商会というブログで生き恥を晒しつつ、最近はYouTubeでゲーム実況を始めました。いいね下さい。チャンネル登録お願いします。", "photoIndex": 7  },
  {  "name" : "村田裕章",  "kana" : "むらたひろあき",  "email" : "ryumagazine@gmail.com",  "birthday" : "10月27日",  "pref" : "大阪府",  "city" : "門真市",  "town" : "北島町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "主にファッション関係のモデルをやっています。ぱくたそさんを通してお仕事はもちろん、自身のPRになったらと思っています。", "photoIndex": 6  },
  {  "name" : "まーちゃん",  "kana" : "まーちゃん",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "大阪府",  "city" : "門真市",  "town" : "北島町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "86才、普通のおじいちゃんです。ひ孫が2人生まれて幸せな日々です。お酒と盆栽が大好き。", "photoIndex": 1  },
  ]

export default pakutasoUsers;