const pakutasoUsers = [
  { "pid": 0, "name" : "河村友歌",  "kana" : "かわむらゆか",  "email" : "xmasyk0519@gmail.com",  "birthday" : "5月19日",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "初めまして！河村友歌（かわむらゆか）です！現役大学生でフリーモデルをやってます(^^)♪いつまでも初心を忘れず、新しい挑戦をたくさんしたいと思ってます♪皆様からのお仕事、お待ちしております（＾Ｏ＾☆" },
  { "pid": 1, "name" : "まーちゃん",  "kana" : "まーちゃん",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "86才、普通のおじいちゃんです。ひ孫が2人生まれて幸せな日々です。お酒と盆栽が大好き。"  },
  { "pid": 2, "name" : "まめち",  "kana" : "まめち",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "自称・日本一インターネットで顔写真が使われているフリー素材モデルです。ぱくたそのモデル兼広報担当としてFacebookページの運用をしております。お仕事ください。" },
  { "pid": 3, "name" : "井隼そら",  "kana" : "いはやそら",  "email" : "ihaya@example.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "慶應義塾大学に通う二年生です。まだまだ不慣れですが、ご希望に応えられるよう精一杯頑張りますので、宜しくお願いします！お仕事、お待ちしております。" },
  { "pid": 4, "name" : "茜さや",  "kana" : "あかねさや",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "広島なまりが少しぬけない狸顔( ˙ω˙ )よく泣いてよく食べます（むちむちなのはご愛嬌）ミスヤンチャンファイナリスト"},
  { "pid": 5, "name" : "大川竜弥",  "kana" : "おおかわりゅうや",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "自称・日本一インターネットで顔写真が使われているフリー素材モデルです。ぱくたそのモデル兼広報担当としてFacebookページの運用をしております。お仕事ください。" },
  { "pid": 6, "name" : "村田裕章",  "kana" : "むらたひろあき",  "email" : "ryumagazine@gmail.com",  "birthday" : "10月27日",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "主にファッション関係のモデルをやっています。ぱくたそさんを通してお仕事はもちろん、自身のPRになったらと思っています。"  },
  { "pid": 7, "name" : "段田隼人",  "kana" : "だんだはやと",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "どうも段田です。普段は株式会社Hyraxでエンジニアとして働いている豚です。豚なんです。段田商会というブログで生き恥を晒しつつ、最近はYouTubeでゲーム実況を始めました。いいね下さい。チャンネル登録お願いします。"  },
  { "pid": 8, "name" : "HOBIJO",  "kana" : "HOBIJO",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "普段はお酒屋さんで写真撮影、ホームページ制作、イラスト制作をしています。"  },
  { "pid": 9, "name" : "Humanbomb",  "kana" : "Humanbomb",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "Humanbomb、本名Jonny Cheng。香港のプロプレイヤー。ストリートファイターVでは春麗を使用。"  },
  { "pid": 10, "name" : "まーこ / 滝沢洞風",  "kana" : "まーこ",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "古武術天心流兵法の代範をしながらモデルをしております。刀以外にも、槍、薙刀、手裏剣、弓等もたしなみます。普段から和装で生活しており、男物の着付けも致します。装束や武具などの骨董も好きで、装束を着装しての演武も可能です！どうぞよろしくお願いいたします。"  },
  { "pid": 11, "name" : "塩田みう",  "kana" : "しおたみう",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "女優 (20) 2015.16.17年度高校野球長崎大会イメージガール/映画「こはく」/映画「しらあいの赦」/ALL！V・ファーレン アシスタント /岩崎本舗 角煮まんじゅうCM などに出演しています。"  },
  { "pid": 12, "name" : "竹田匡宏",  "kana" : "だんだはやと",  "email" : "ryumagazine@gmail.com",  "birthday" : "2021/2/8",  "pref" : "東京都",  "city" : "渋谷区",  "town" : "桜丘町",  "add1" : "",  "add2" : "589",  "add3" : "13",  "introduce" : "基本的に何でもやってみたいというスタンスなので、NGは出しません！宜しくお願いします！"  }
  ]

export default pakutasoUsers;